---
- hosts: all
  become: true
  gather_facts: yes
  tasks:
    - name: Placeholder tasks
      command: cat /etc/redhat-release
      register: cmd_out

    - debug: var={{item}}
      with_items: cmd_out.stdout_lines
