---
- hosts: all
  become: true
  gather_facts: yes
  collections:
    - ch_collections.base
  roles:
    - role: ch_collections.base.os_package_control
      vars:
        update_os: "{{ update_packages | default(false) }}"

  tasks:
    - name: Placeholder tasks
      command: cat /etc/redhat-release
      register: cmd_out

    - debug: var={{item}}
      with_items: cmd_out.stdout_lines

