---
- hosts: all
  become: true
  gather_facts: yes
  roles:
    - role: ch_collections.base.os_package_control
      vars:
        update_os: "{{ update_packages | default(false) }}"
    - role: oracle-19

  tasks:
